[package]
name = "prakt1-2"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
num-bigint-dig = "*"
num-traits = "0.2"
num-prime = "0.4"
rayon = "1.5"